---

- name: setup-Redhat | Downloading and enable the EPEL repository definitions.
  package:
    name: epel-release
    state: present
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "7" or ansible_distribution_major_version == "8"

- name: setup-Redhat | install apache
  yum:
    pkg: "{{ apache_packages }}"
    state: present

- name: setup-Redhat | Install Nagios prerequisites for CentOS
  yum:
    pkg: "{{ nagios_plugins_deps }}"
    state: present
