# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure(2) do |config|

  config.vm.define "centos6" do |centos6|
    centos6.vm.box = "geerlingguy/centos6"

    centos6.vm.provision "shell", inline: <<-SHELL
      sudo yum -y update
      sudo yum clean all
      sudo yum -y install epel-release
      sudo yum -y install git ansible sudo
      sudo yum clean all
      # sudo echo -e '[local]\nlocalhost ansible_connection=local' > /etc/ansible/hosts
    SHELL

  end

  config.vm.define "ubuntu12" do |ubuntu12|
    ubuntu12.vm.box = "hashicorp/precise64"

    ubuntu12.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
    SHELL
  end

  config.vm.define "ubuntu14" do |ubuntu14|
    ubuntu14.vm.box = "ubuntu/trusty64"

    ubuntu14.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
    SHELL
  end

end
