# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure(2) do |config|

  config.vm.define "centos6" do |centos6|
    centos6.vm.box = "geerlingguy/centos6"

    centos6.vm.provision "shell", inline: <<-SHELL
      sudo yum -y update
      sudo yum clean all
      sudo yum -y install epel-release
      sudo yum -y install git ansible sudo
      sudo yum clean all
      sudo echo -e '[local]\nlocalhost ansible_connection=local' > /etc/ansible/hosts
    SHELL
    centos6.vm.synced_folder "../", "/etc/ansible/roles/ansible-role-nagios", :mount_options => ["ro"]
    centos6.vm.network "forwarded_port", guest: 80, host: 8006
  end

  config.vm.define "centos7" do |centos7|
    centos7.vm.box = "geerlingguy/centos7"

    centos7.vm.provision "shell", inline: <<-SHELL
      sudo yum -y update
      sudo yum clean all
      #sudo yum -y install epel-release
      #sudo yum -y install git ansible sudo
      sudo yum clean all
      sudo echo -e '[local]\nlocalhost ansible_connection=local' > /etc/ansible/hosts
    SHELL
    centos7.vm.synced_folder "../", "/etc/ansible/roles/ansible-role-nagios", :mount_options => ["ro"]
  end

  config.vm.define "debian8" do |debian8|
    debian8.vm.box = "deb/jessie-amd64"

    debian8.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install -y software-properties-common git
      # sudo apt-add-repository -y ppa:ansible/ansible
      sudo apt-get update
      sudo apt-get install -y ansible
      sudo echo "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts
    SHELL
    debian8.vm.synced_folder "../", "/etc/ansible/roles/ansible-role-nagios", :mount_options => ["ro"]
  end

  config.vm.define "ubuntu12" do |ubuntu12|
    ubuntu12.vm.box = "hashicorp/precise64"

    ubuntu12.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install -y software-properties-common python-software-properties git
      sudo apt-add-repository -y ppa:ansible/ansible
      sudo apt-get update
      sudo apt-get install -y ansible
      sudo echo "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts
    SHELL
    ubuntu12.vm.synced_folder "../", "/etc/ansible/roles/ansible-role-nagios", :mount_options => ["ro"]
    ubuntu12.vm.network "forwarded_port", guest: 80, host: 8012
  end

  config.vm.define "ubuntu14" do |ubuntu14|
    ubuntu14.vm.box = "ubuntu/trusty64"

    ubuntu14.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install -y software-properties-common
      sudo apt-add-repository -y ppa:ansible/ansible
      sudo apt-get update
      sudo apt-get install -y ansible
      sudo echo "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts
    SHELL
    ubuntu14.vm.synced_folder "../", "/etc/ansible/roles/ansible-role-nagios", :mount_options => ["ro"]
    ubuntu14.vm.network "forwarded_port", guest: 80, host: 8014
  end

  config.vm.define "ubuntu16" do |ubuntu16|
    ubuntu16.vm.box = "gbarbieru/xenial"

    ubuntu16.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      #sudo apt-get install -y software-properties-common
      #sudo apt-add-repository -y ppa:ansible/ansible
      #sudo apt-get update
      sudo apt-get install -y ansible
      sudo echo "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts
    SHELL
    ubuntu16.vm.synced_folder "../", "/etc/ansible/roles/ansible-role-nagios", :mount_options => ["ro"]
    ubuntu16.vm.network "forwarded_port", guest: 80, host: 8016
  end


end
