---
# handlers file for nagios
- name: restart apache
  ansible.builtin.systemd:
    name: "{{ apache_service }}"
    state: restarted

- name: restart nagios
  ansible.builtin.systemd:
    name: nagios
    state: restarted
    daemon_reload: yes
